accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("update/", views.update, name="update"),
    path("delete/", views.delete, name="delete"),
    path("password/", views.password, name="password"),
    path("<int:user_pk>/detail/", views.detail, name="detail"),
    path("<int:user_pk>/follow/", views.follow, name="follow"),
    path("<int:user_pk>/block/", views.block, name="block"),
    path("<int:user_pk>/wishlist/", views.wishlist, name="wishlist"),
]

articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path("", views.index, name="index"),
    path("product_list/<category_pk>/", views.product_list, name='product_list'),
    path("product_create/", views.product_create, name='product_create'),
    path("<int:product_pk>/product_detail/", views.product_detail, name='product_detail'),
    path("<int:product_pk>/product_update/", views.product_update, name='product_update'),
    path("<int:product_pk>/product_delete/", views.product_delete, name='product_delete'),
    path("review_index/", views.review_index, name='review_index'),
    path('<int:product_pk>/like/', views.like, name='like'),
    path("<int:product_pk>/review_create/", views.review_create, name='review_create'),
    path("<int:review_pk>/review_update/", views.review_update, name='review_update'),
    path("<int:product_pk>/review_delete/<int:review_pk>/", views.review_delete, name='review_delete'),
    path("<int:review_pk>/review_comment_create/", views.review_comment_create, name='review_comment_create'),
    path("<int:comment_pk>/review_comment_delete/", views.review_comment_delete, name='review_comment_delete'),
    path('product_rank/', views.product_rank, name='product_rank'),
    path('product_rank_redirect/', views.product_rank_redirect, name='product_rank_redirect'),
    path('search/', views.search, name='search'),
    path("<int:review_pk>/review_good/", views.review_good, name='review_good'),
    path("<int:review_pk>/review_cool/", views.review_cool, name='review_cool'),
    path("<int:review_pk>/review_fun/", views.review_fun, name='review_fun'),
    path("<int:review_pk>/review_sad/", views.review_sad, name='review_sad'),
    path("community_index/", views.community_index, name='community_index'),
    path("community_create/", views.community_create, name='community_create'),
    path("<int:community_pk>/community_update/", views.community_update, name='community_update'),
    path("<int:community_pk>/community_delete/", views.community_delete, name='community_delete'),
    path("<int:community_pk>/community_detail/", views.community_detail, name='community_detail'),
    path("<int:community_pk>/community_comment_create/", views.community_comment_create, name='community_comment_create'),
    path("<int:comment_pk>/community_comment_delete/", views.community_comment_delete, name='community_comment_delete'),
    path('<int:community_pk>/community_like/', views.community_like, name='community_like'),
    path("md_jsm/", views.md_jsm, name='md_jsm'),
    path("md_kbw/", views.md_kbw, name='md_kbw'),
    path("md_kkh/", views.md_kkh, name='md_kkh'),
]

pjt_OJD/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("articles.urls")),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("allauth.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.


class User(AbstractUser):
    nickname = models.CharField(max_length=20, unique=True)
    image = ProcessedImageField(
        upload_to="images/",
        null=True,
        blank=True,
        processors=[Thumbnail(400, 400)],
        format="JPEG",
        options={"quality": 80},
    )
    gender = models.BooleanField(default=False)
    birth_date = models.DateField(null=True)
    following = models.ManyToManyField(
        "self", symmetrical=False, related_name="followers"
    )
    blocking = models.ManyToManyField(
        "self", symmetrical=False, related_name="blockers"
    )
    age = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(15)], null=True
    )

    # user image 없을 시 오류 방지
    @property
    def get_photo_url(self):
        if self.image:
            return self.image.url
        return "../static/images/no-avatar.jpg"

articles/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill, Thumbnail
from django.core.validators import MinValueValidator, MaxValueValidator
from datetime import datetime
from ckeditor.fields import RichTextField
# Create your models here.


class Product(models.Model):
    category_choice = ( 
            ("1", "생일"),
            ("2", "가벼운 선물"),
            ("3", "건강/회복"),
            ("4", "스몰럭셔리"),
            ("5", "어른선물"),
            ("6", "크리스마스"),
            ("7", "명품선물"),
            ("8", "출산/키즈"),
            ("9", "따뜻한선물"),
            ("11", "배달선물"),
        )
    title = models.CharField(max_length=100)
    brand= models.CharField(max_length=50, null=True)
    product_url = models.CharField(max_length=100, null=True)
    content = models.TextField(null=True)
    category = models.CharField(max_length=2, choices=category_choice)
    price = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True
    )
    like_user = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="like_product"
    )


class ProductImages(models.Model):
    product = models.ForeignKey("Product", on_delete=models.CASCADE)
    images = models.CharField(max_length=300)


class ProductContentImages(models.Model):
    product = models.ForeignKey("Product", on_delete=models.CASCADE)
    images = models.CharField(max_length=300)


class Review(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    image = ProcessedImageField(
        upload_to="images/",
        blank=True,
        processors=[ResizeToFill(400, 300)],
        format="JPEG",
        options={"quality": 80},
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    rating = models.IntegerField(
        default=3, validators=[MinValueValidator(1), MaxValueValidator(5)]
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey("Product", on_delete=models.CASCADE)
    good_user = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="good_review"
    )
    cool_user = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="cool_review"
    )
    fun_user = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="fun_review"
    )
    sad_user = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="sad_review"
    )


class ReviewComment(models.Model):
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    review = models.ForeignKey('Review', on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


class Community(models.Model):
    title = models.CharField(max_length=20)
    content = RichTextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_community')
    hits = models.PositiveIntegerField(default=0)
    

class CommunityImages(models.Model):
    community = models.ForeignKey("Community", on_delete=models.CASCADE)
    images = ProcessedImageField(
        upload_to="images/",
        blank=True,
        processors=[ResizeToFill(400, 300)],
        format="JPEG",
        options={"quality": 80},
    )
    
class CommunityComment(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    community = models.ForeignKey('Community', on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth import get_user_model


class SignupForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = (
            "username",
            "email",
            "password1",
            "password2",
            "nickname",
            "image",
            "gender",
            "birth_date",
        )


class UpdateForm(UserChangeForm):
    password = None  # profile_update에서 password를 없애기 위함. exclude로는 안됨.

    class Meta:
        model = get_user_model()
        fields = (
            "email",
            "nickname",
            "gender",
            "image",
        )
        widgets = {
            "email": forms.TextInput(
                attrs={
                    "class": "focus-effect form-control-plaintext",
                    "help_text": "ID는 수정할 수 없습니다.",
                },
            ),
            "nickname": forms.TextInput(
                attrs={
                    "class": "focus-effect",
                    "help_text": "변경할 닉네임을 입력해주세요.",
                },
            ),
        }

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from accounts.forms import SignupForm, UpdateForm
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import get_user_model
from django.contrib import messages
from django.http import JsonResponse
from django.core.paginator import Paginator
from datetime import datetime
import time

# Create your views here.


def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = request.POST.get("username")
            user.email = request.POST.get("username")
            age_range = (datetime.today().year - user.birth_date.year) // 10
            if age_range < 0 or age_range > 15:
                messages.error(request, "유효한 생년월일이 아닙니다.")
                return redirect("articles:index")
            user.age = age_range
            user.save()
            auth_login(
                request, user, backend="django.contrib.auth.backends.ModelBackend"
            )
        else:
            messages.error(request, "유효하지 않은 정보입니다.")
        return redirect("articles:index")
    else:
        form = SignupForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/signup.html", context)


def login(request):
    if request.user.is_anonymous:
        if request.method == "POST":
            form = AuthenticationForm(request, data=request.POST)
            if form.is_valid():
                auth_login(request, form.get_user())
                return redirect(request.GET.get("next") or "articles:index")
            else:
                messages.warning(request, "아이디 혹은 비밀번호가 틀렸습니다.")
                return redirect("accounts:login")
        else:
            form = AuthenticationForm()

        context = {
            "form": form,
        }
        return render(request, "accounts/login.html", context)
    else:
        return redirect("articles:index")


@login_required
def logout(request):
    auth_logout(request)
    return redirect("accounts:login")


@login_required
def update(request):
    if request.user.is_authenticated:
        if request.method == "POST":
            form = UpdateForm(request.POST, request.FILES, instance=request.user)
            print(form)
            if form.is_valid():
                form.save()
                messages.success(request, "수정되었습니다.")
            else:
                messages.warning(request, "유효하지 않은 양식입니다.")
            return redirect("accounts:detail", request.user.pk)
        else:
            form = UpdateForm(instance=request.user)
        context = {
            "form": form,
        }
        return render(request, "accounts/update.html", context)
    else:
        messages.warning(request, "로그인 후 이용할 수 있습니다.")
        return redirect("accounts:login")


@login_required
def delete(request):
    if request.method == "POST":
        request.user.delete()
        auth_logout(request)
        messages.success(request, "성공적으로 탈퇴되었습니다.")
    return redirect("articles:index")


@login_required
def password(request):
    if request.user.is_authenticated:
        if request.method == "POST":
            form = PasswordChangeForm(request.user, request.POST)
            if form.is_valid():
                form.save()
                update_session_auth_hash(request, form.user)
                messages.success(request, "변경되었습니다.")
            return redirect("accounts:update")
        else:
            form = PasswordChangeForm(request.user)
        context = {
            "form": form,
        }
        return render(request, "accounts/password.html", context)
    else:
        messages.warning(request, "로그인 후 이용할 수 있습니다.")
        return redirect("accounts:login")


def detail(request, user_pk):
    user = get_object_or_404(get_user_model(), pk=user_pk)

    posts = user.community_set.all().order_by("-id")
    posts_page = request.GET.get("page", "1")  # GET 방식으로 정보를 받아오는 데이터
    posts_paginator = Paginator(posts, "3")  # Paginator(분할될 객체, 페이지 당 담길 객체수)
    paginated_posts = posts_paginator.get_page(posts_page)

    review_list = user.review_set.all().order_by("-id")  # 데이터 역순 정렬
    page = request.GET.get("page", "1")  # GET 방식으로 정보를 받아오는 데이터
    paginator = Paginator(review_list, "4")  # Paginator(분할될 객체, 페이지 당 담길 객체수)
    paginated_review_list = paginator.get_page(page)  # 페이지 번호를 받아 해당 페이지를 리턴

    wishlist = user.like_product.all().order_by("-id")
    wishlist_page = request.GET.get("page", "1")  # GET 방식으로 정보를 받아오는 데이터
    wishlist_paginator = Paginator(wishlist, "3")  # Paginator(분할될 객체, 페이지 당 담길 객체수)
    paginated_wishlist = wishlist_paginator.get_page(wishlist_page)

    context = {
        "user": user,
        "paginated_post_list": paginated_posts,
        "paginated_review_list": paginated_review_list,
        "paginated_wishlist": paginated_wishlist,
    }
    return render(request, "accounts/detail.html", context)


def follow(request, user_pk):
    if request.user.is_authenticated:
        user = get_object_or_404(get_user_model(), pk=user_pk)
        if request.user != user:
            if user.followers.filter(pk=request.user.pk).exists():
                user.followers.remove(request.user)
                is_followed = False
            else:
                user.followers.add(request.user)
                is_followed = True
            context = {
                "is_followed": is_followed,
                "followings_count": user.following.count(),
                "followers_count": user.followers.count(),
            }
            return JsonResponse(context)
        else:
            messages.error(request, "자신은 팔로우할 수 없습니다.")
        return redirect("accounts:detail", user_pk)
    else:
        messages.warning(request, "로그인 후 이용할 수 있습니다.")
        return redirect("accounts:login")


def block(request, user_pk):
    if request.user.is_authenticated:
        user = get_object_or_404(get_user_model(), pk=user_pk)
        if request.user != user:
            if user.blockers.filter(pk=request.user.pk).exists():
                user.blockers.remove(request.user)
                is_blocked = False
            else:
                user.blockers.add(request.user)
                is_blocked = True
            context = {
                "is_blocked": is_blocked,
            }
            return JsonResponse(context)
        else:
            messages.error(request, "자신은 차단할 수 없습니다.")
        return redirect("accounts:detail", user_pk)
    else:
        messages.warning(request, "로그인 후 이용할 수 있습니다.")
        return redirect("accounts:login")


def wishlist(request, user_pk):
    context = {
        "user": get_object_or_404(get_user_model(), pk=user_pk),
    }
    return render(request, "accounts/wishlist.html", context)

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% load static %}
{% load widget_tweaks %}
{% load django_bootstrap5 %}
{% load imagekit %}
{% load socialaccount %}
{% providers_media_js %}

{% block title %} | 로그인{% endblock title %}
{% block style %}{% endblock style %}
{% block content %}

<section class="container accounts-wrapper">
  <form action="{% url 'accounts:login' %}" method="POST" onsubmit="return frm_check();">
    {% csrf_token %}
    <label for="email">아이디</label>
    <div class="login-field">
      {% render_field form.username class="focus-effect" placeholder="이메일을 입력하세요" type="email" name="email" id="logId" %}
      <span class="focus-border">
        <i></i>
      </span>
    </div>
    <label for="password">비밀번호</label>
    <div class="login-field">
      {% render_field form.password class="focus-effect" placeholder="비밀번호를 입력하세요" type="password" name="password" autocomplete="false" id="key" onkeyup="checkCapsLock(event)" %}
      <span class="focus-border">
        <i></i>
      </span>
      <div id="keyShow">SHOW</div> 
    </div>
    <div id='message'></div>
    <div class="input-wrap">
      <input type="checkbox" name="saveId" id="saveId">
      <label for="saveId">아이디 저장</label>
    </div>
    <button class="pos-btn login-button" type='submit' content='로그인' id="checkKey">로그인</button>
  </form>
  <p class="text-center">아직 회원이 아니신가요?
    <a class="text-decoration-none" href="{% url 'accounts:signup' %}"><b>회원가입</b></a>
  </p>
  <div class="hr-sect">또는</div>
  <p>SNS계정으로 간편 로그인 / 회원가입</p>
  <!--소셜 로그인-->
  <div class="d-flex justify-content-center my-0">
    <form action="/accounts/google/login/" method="post">
      {% csrf_token %}
      <button class="btn btn-link my-2 my-sm-0 py-1" style="color : #FFFFFF" type="submit"
        onclick="document.getElementById('test').submit();"><img src="{% static 'img/google.png' %}" alt="구글"
          style="height:55px;"></button>
    </form>
    <form class="mx-1" action="/accounts/kakao/login/" method="post">
      {% csrf_token %}
      <button class="btn btn-link my-2 my-sm-0 py-1" style="color : #FFFFFF" type="submit"
        onclick="document.getElementById('test').submit();"><img src="{% static 'img/kakao.png' %}" alt="카카오"
          style="height:55px;"></button>
    </form>
    <form action="/accounts/naver/login/" method="post">
      {% csrf_token %}
      <button class="btn my-2 my-sm-0 btn-l py-1" style="color : #FFFFFF" type="submit"
        onclick="document.getElementById('test').submit();"><img src="{% static 'img/naver.png' %}" alt="네이버"
          style="height:55px;"></button>
    </form>
  </div><!--소셜 로그인 끝--> 
</section>
{% endblock content %}
{% block script %}
<!--아이디 저장-->
<script>
  $(function () {
    fnInit();
  });

  function frm_check() {
    saveid();
  }
  
  function fnInit() {
    var cookieid = getCookie("saveid");
    console.log(cookieid);
    if (cookieid != "") {
      $("input:checkbox[id='saveId']").prop("checked", true);
      $('#logId').val(cookieid);
    }
  }

  function setCookie(name, value, expiredays) {
    var todayDate = new Date();
    todayDate.setTime(todayDate.getTime() + 0);
    if (todayDate > expiredays) {
      document.cookie = name + "=" + escape(value) + "; path=/; expires=" + expiredays + ";";
    } else if (todayDate < expiredays) {
      todayDate.setDate(todayDate.getDate() + expiredays);
      document.cookie = name + "=" + escape(value) + "; path=/; expires=" + todayDate.toGMTString() + ";";
    }
    console.log(document.cookie);
  }

  function getCookie(Name) {
    var search = Name + "=";
    console.log("search : " + search);
    if (document.cookie.length > 0) { // 쿠키가 설정되어 있다면
      offset = document
        .cookie
        .indexOf(search);
      console.log("offset : " + offset);
      if (offset != -1) { // 쿠키가 존재하면
        offset += search.length;
        // set index of beginning of value
        end = document
          .cookie
          .indexOf(";", offset);
        console.log("end : " + end);
        // 쿠키 값의 마지막 위치 인덱스 번호 설정
        if (end == -1) 
          end = document.cookie.length;
        console.log("end위치  : " + end);
        return unescape(document.cookie.substring(offset, end));
      }
    }
    return "";
  }

  function saveid() {
    var expdate = new Date();
    if ($("#saveId").is(":checked")) {
      expdate.setTime(expdate.getTime() + 1000 * 3600 * 24 * 30);
      setCookie("saveid", $("#logId").val(), expdate);
    } else {
      expdate.setTime(expdate.getTime() - 1000 * 3600 * 24 * 30);
      setCookie("saveid", $("#logId").val(), expdate);
    }
  }
</script>
<!--비밀번호 보이기-->
<script>
  $("#key").on("keyup", function(event) {
    if (event.keyCode === 13) {
      event.preventDefault();
      $("#checkKey").triggerHandler("click");
    } else {
      if (this.value) {
        $("#keyShow").css("display", "inline-block");
      } else {
        $("#keyShow").hide();
      }
    }
  }).focus();
  
  $("#keyShow").on("click", function() {
    if ($("#key").attr("type") == "password") {
      $("#key").attr("type", "text");
      $($(this)).text("H I D E");
    } else {
      $("#key").attr("type", "password");
      $($(this)).text("SHOW");
    }
  });
</script>
<!--캡스락 경고-->
<script>
  function checkCapsLock(event)  {
    if (event.getModifierState("CapsLock")) {
      document.getElementById("message").innerHTML 
        = "<i class='bi bi-exclamation-octagon'></i>" + "&nbspCaps Lock이 켜져 있습니다."
    }else {
      document.getElementById("message").innerText 
        = ""
    }
  }
</script>
{% endblock script %}

accounts/templates/accounts/password.html
{% extends 'base.html' %}

{% load static %}
{% load widget_tweaks %}
{% load django_bootstrap5 %}
{% load imagekit %}

{% block title %} | 비밀번호 변경{% endblock title %}
{% block style %}{% endblock style %}

{% block content %}
<section class="content-wrapper">
  <div class="signup-wrapper">
    <h1 class="text-center">비밀번호 변경</h1>
    <form action="" method="POST">
      {% csrf_token %}
      <div class="mb-1 d-flex flex-column align-items-center"><label class="form-label" for="id_old_password">기존
          비밀번호</label><input type="password" name="old_password" autocomplete="current-password" autofocus=""
          class="password-style1" required="" id="id_old_password">
      </div>
      <div class="mb-1 d-flex flex-column align-items-center"><label class="form-label" for="id_new_password1">새
          비밀번호</label><input type="password" name="new_password1" autocomplete="new-password" class="password-style1"
          required="" id="id_new_password1">
      </div>
      <div class="mb-1 d-flex flex-column align-items-center"><label class="form-label" for="id_new_password2">새 비밀번호
          (확인)</label><input type="password" name="new_password2" autocomplete="new-password" class="password-style1"
          required="" id="id_new_password2">
      </div>
      <button class="login-button" type="submit">비밀번호 변경</button>
    </form>
  </div>
</section>
{% endblock content %}

{% block script %}{% endblock script %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% load static %}
{% load widget_tweaks %}
{% load django_bootstrap5 %}
{% load imagekit %}

{% block title %} | 프로필 수정{% endblock title %}
{% block style %}{% endblock style %}

{% block content %}
<section class="container accounts-wrapper">
  <h1 class="text-center">프로필 수정</h1>
  <form class='w-100' action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <h3 for="email">아이디</h3>
    <div class="login-field">
      <input type="email" name="username" value="{{ request.user.username }}" maxlength="254" class="focus-effect w-100 text-center" aria-label="Disabled input example" disabled readonly id="id_email">
      <span class="focus-border">
        <i></i>
      </span>
    </div>
    <h3 for="nickname">닉네임</h3>
    <div class="login-field text-center">
      {% render_field form.nickname class="focus-effect w-100 text-center"%}
      <span class="focus-border">
        <i></i>
      </span>
    </div>
    <h3 for="password">비밀번호</h3>
    <div class="login-field">
      <a class="focus-effect w-100" href="{% url 'accounts:password' %}">변경 페이지 바로가기 <i class="bi bi-arrow-right-circle-fill"></i></a>
      <span class="focus-border">
        <i></i>
      </span>
    </div>

    <h3 for="image">프로필 사진</h3>
    <div class="login-field">
      {% render_field form.image type="file" class="focus-effect w-100" name="image" %}
      <span class="focus-border">
        <i></i>
      </span>
    </div>
    
    <h3 for="gender">성별</h3>
    <div class="login-field">
      <p class="focus-effect w-100" name="gender">
        {% if user.gender == True %}
        남자
        {% else %}
        여자
        {% endif %}</p>
      <span class="focus-border">
        <i></i>
      </span>
    </div>
    
    <input class="login-button neg-btn" type="submit" value="저장">
  </form>
</section>
{% endblock content %}

{% block script %}{% endblock script %}

accounts/templates/accounts/wishlist.html
{% extends 'base.html' %}

{% load static %}
{% load widget_tweaks %}
{% load django_bootstrap5 %}
{% load imagekit %}

{% block title %} | 위시리스트{% endblock title %}
{% block style %}
{% endblock style %}

{% block content %}
  <section class="content-wrapper">
      <h1>{{ user.nickname }} 님은 이런 선물을 받고 싶어해요.</h1>
      <span>{{ user.nickname }} 님이 최근 1년간 추가한 상품 내역이 제공됩니다.</span>
      <span></span>
      <hr>
    {% if user.like_product.all %}
    <div class="swiper">
      <!-- Additional required wrapper -->
      <div class="swiper-wrapper">
        <!-- Slides -->
        {% for product in user.like_product.all %}
        <div class="swiper-slide mb-5 d-flex flex-column align-items-center">
          <img class="review-image" src="{{ product.productimages_set.all.0.images }}">
          <div class="word"><a href="{% url 'articles:product_detail' product.pk %}">{{ product.title }}</a></div>
        </div>
        {% endfor %}
      </div>
      <!-- If we need pagination -->
      <div class="swiper-pagination"></div>
      <!-- If we need navigation buttons -->
      <div class="swiper-button-prev"></div>
      <div class="swiper-button-next"></div>
    </div>
    {% else %}
    <div class="text-center my-5">관심상품 내역이 없습니다.</div>
    {% endif %}
  </section>
{% endblock content %}            
{% block script %}

<script>
  const swiper = new Swiper('.swiper', {
    // Optional parameters
    direction: 'horizontal',
    slidesPerView: 3,
    loop: true,
    // If we need pagination
    pagination: {
      el: '.swiper-pagination',
      clickable: true,
    },

    // Navigation arrows
    navigation: {
      nextEl: '.swiper-button-next',
      prevEl: '.swiper-button-prev',
    },

  });</script>
{% endblock script %}