accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("update/", views.update, name="update"),
    path("delete/", views.delete, name="delete"),
    path("password/", views.password, name="password"),
    path("<int:user_pk>/detail/", views.detail, name="detail"),
    path("<int:user_pk>/follow/", views.follow, name="follow"),
    path("<int:user_pk>/block/", views.block, name="block"),
    path("<int:user_pk>/wishlist/", views.wishlist, name="wishlist"),
]

articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path("", views.index, name="index"),
    path("product_list/<category_pk>/", views.product_list, name='product_list'),
    path("product_create/", views.product_create, name='product_create'),
    path("<int:product_pk>/product_detail/", views.product_detail, name='product_detail'),
    path("<int:product_pk>/product_update/", views.product_update, name='product_update'),
    path("<int:product_pk>/product_delete/", views.product_delete, name='product_delete'),
    path("review_index/", views.review_index, name='review_index'),
    path('<int:product_pk>/like/', views.like, name='like'),
    path("<int:product_pk>/review_create/", views.review_create, name='review_create'),
    path("<int:review_pk>/review_update/", views.review_update, name='review_update'),
    path("<int:product_pk>/review_delete/<int:review_pk>/", views.review_delete, name='review_delete'),
    path("<int:review_pk>/review_comment_create/", views.review_comment_create, name='review_comment_create'),
    path("<int:comment_pk>/review_comment_delete/", views.review_comment_delete, name='review_comment_delete'),
    path('product_rank/', views.product_rank, name='product_rank'),
    path('product_rank_redirect/', views.product_rank_redirect, name='product_rank_redirect'),
    path('search/', views.search, name='search'),
    path("<int:review_pk>/review_good/", views.review_good, name='review_good'),
    path("<int:review_pk>/review_cool/", views.review_cool, name='review_cool'),
    path("<int:review_pk>/review_fun/", views.review_fun, name='review_fun'),
    path("<int:review_pk>/review_sad/", views.review_sad, name='review_sad'),
    path("community_index/", views.community_index, name='community_index'),
    path("community_create/", views.community_create, name='community_create'),
    path("<int:community_pk>/community_update/", views.community_update, name='community_update'),
    path("<int:community_pk>/community_delete/", views.community_delete, name='community_delete'),
    path("<int:community_pk>/community_detail/", views.community_detail, name='community_detail'),
    path("<int:community_pk>/community_comment_create/", views.community_comment_create, name='community_comment_create'),
    path("<int:comment_pk>/community_comment_delete/", views.community_comment_delete, name='community_comment_delete'),
    path('<int:community_pk>/community_like/', views.community_like, name='community_like'),
    path("md_jsm/", views.md_jsm, name='md_jsm'),
    path("md_kbw/", views.md_kbw, name='md_kbw'),
    path("md_kkh/", views.md_kkh, name='md_kkh'),
]

pjt_OJD/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("articles.urls")),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("allauth.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill, Thumbnail
from django.core.validators import MinValueValidator, MaxValueValidator
from datetime import datetime
from ckeditor.fields import RichTextField
# Create your models here.


class Product(models.Model):
    category_choice = ( 
            ("1", "생일"),
            ("2", "가벼운 선물"),
            ("3", "건강/회복"),
            ("4", "스몰럭셔리"),
            ("5", "어른선물"),
            ("6", "크리스마스"),
            ("7", "명품선물"),
            ("8", "출산/키즈"),
            ("9", "따뜻한선물"),
            ("11", "배달선물"),
        )
    title = models.CharField(max_length=100)
    brand= models.CharField(max_length=50, null=True)
    product_url = models.CharField(max_length=100, null=True)
    content = models.TextField(null=True)
    category = models.CharField(max_length=2, choices=category_choice)
    price = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True
    )
    like_user = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="like_product"
    )


class ProductImages(models.Model):
    product = models.ForeignKey("Product", on_delete=models.CASCADE)
    images = models.CharField(max_length=300)


class ProductContentImages(models.Model):
    product = models.ForeignKey("Product", on_delete=models.CASCADE)
    images = models.CharField(max_length=300)


class Review(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    image = ProcessedImageField(
        upload_to="images/",
        blank=True,
        processors=[ResizeToFill(400, 300)],
        format="JPEG",
        options={"quality": 80},
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    rating = models.IntegerField(
        default=3, validators=[MinValueValidator(1), MaxValueValidator(5)]
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey("Product", on_delete=models.CASCADE)
    good_user = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="good_review"
    )
    cool_user = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="cool_review"
    )
    fun_user = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="fun_review"
    )
    sad_user = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="sad_review"
    )


class ReviewComment(models.Model):
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    review = models.ForeignKey('Review', on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


class Community(models.Model):
    title = models.CharField(max_length=20)
    content = RichTextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_community')
    hits = models.PositiveIntegerField(default=0)
    

class CommunityImages(models.Model):
    community = models.ForeignKey("Community", on_delete=models.CASCADE)
    images = ProcessedImageField(
        upload_to="images/",
        blank=True,
        processors=[ResizeToFill(400, 300)],
        format="JPEG",
        options={"quality": 80},
    )
    
class CommunityComment(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    community = models.ForeignKey('Community', on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

articles/forms.py
from django import forms
from django.forms import ClearableFileInput
from .models import *


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ("title", "content", "category", "price")


class ProductImagesForm(forms.ModelForm):
    class Meta:
        model = ProductImages
        fields = ("images",)
        widgets = {
            "images": ClearableFileInput(attrs={"multiple": True}),
        }
        labels = {
            "images": "이미지 업로드",
        }


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ("title", "content", "image", "rating")
        labels = {
            "title": '제목',
            "content": '내용',
            "image": '이미지',
            "rating": '평점(1 ~ 5 사이 값을 입력해주세요)',
        }


class ReviewCommentForm(forms.ModelForm):
    class Meta:
        model = ReviewComment
        fields = ("content",)


class CommunityForm(forms.ModelForm):
    
    class Meta:
        model = Community
        fields = ("title", "content")
        labels = {
            "title": "",
            "content": "",
        }


class CommunityImagesForm(forms.ModelForm):
    class Meta:
        model = CommunityImages
        fields = ("images",)
        widgets = {
            "images": ClearableFileInput(attrs={"multiple": True}),
        }
        labels = {
            "images": "이미지",
        }


class CommunityCommentForm(forms.ModelForm):
    class Meta:
        model = CommunityComment
        fields = ["content",]
        labels = {
            "content": "댓글을 작성해주세요",
        }

articles/templates/articles/community_detail.html
{% extends 'base.html' %}

{% load static %}
{% load widget_tweaks %}
{% load django_bootstrap5 %}
{% load imagekit %}

{% block title %} | {{ community.title }}{% endblock title %}
{% block style %}
<!-- MDB -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.0.1/mdb.min.css" rel="stylesheet"/>
{% endblock style %}

{% block content %}
  <div class="commu_container">
    <div class="my-2">
      <!-- title -->
      <h1 class='display-6'>{{ community.title }}</h1>
      <!-- 상단 (정보 / menu) -->
      <section class="d-flex justify-content-between my-2">
        <div class="d-flex">
          {% if community.user.image %}
          <img src="{{ community.user.image.url }}" class="commu_pf_img" alt="유저 이미지">
          {% else %}
          <img src="{% static 'img/no-avatar.jpg' %}" class="commu_pf_img" alt="유저 대체이미지">
          {% endif %} 
          <p class='my-1 mx-3'><a href="{% url 'accounts:detail' community.user.pk %}">{{ community.user.nickname }}</a></p>
          <p class="my-1">{{ community.created_at|date:'Y.m.d H:i' }}</p>
        </div>
        <!-- menu (dropdown) -->
        <div class="dropdown">
          <button class="detail_drop btn dropdown-toggle" type="button" id="dropdownMenu2" data-mdb-toggle="dropdown" aria-expanded="false">
            Menu
          </button>
          <ul style="width: 12rem; height: 9.5rem;" class="dropdown-menu" aria-labelledby="dropdownMenu2">
            <li>
              <a href="{% url 'articles:community_index' %}">
                <button class="dropdown-item" type="button">커뮤니티 메인</button>
              </a>
            </li>
            {% if request.user == community.user %}
            <li>
              <a href="{% url 'articles:community_update' community.pk %}">
                <button class="dropdown-item" type="button">글 수정</button>
              </a>
            </li>
            <li>
              <a href="{% url 'articles:community_delete' community.pk %}">
                <button class="dropdown-item" type="button">글 삭제</button>
              </a>
            </li>
            {% else %}
            <li>
              <a href="{% url 'accounts:detail' community.user.pk %}">
                <button class="dropdown-item" type="button">작성자 정보</button>
              </a>
            </li>
            {% endif %}
          </ul>
        </div>
      </section>
    </div>
    <hr class="commu_hr_2">
    <!-- 이미지 (슬라이드) -->
    <div class="my-5">
      <div class="d-flex justify-content-start mb-3">
        <div style="position: relative;">
          {% for i in community.communityimages_set.all %}
          <div class="big_img mySlides">
            <div class="numbertext">{{ forloop.counter }}</div>
            <img class="w-100 h-100" src="{{ i.images.url }}" alt="커뮤니티 이미지">
          </div>
          {% endfor %}
          <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
          <a class="next" onclick="plusSlides(1)">&#10095;</a>
          <div class="d-flex justify-content-center my-2">
            {% for i in community.communityimages_set.all %}
            <span class="dot" onclick="currentSlide({{forloop.counter}})"></span>
            {% endfor %}
          </div>
        </div>
      </div>
      <!-- 글 내용 -->
      <p>{{ community.content|safe }}</p>
      <!-- 좋아요 -->
      <div class="mt-5">
        {% if request.user.is_authenticated %}
          {% if request.user in community.like_users.all %}
              <i id="like-btn" data-community-id="{{ community.pk }}" class="bi bi-heart-fill text-danger"></i>
          {% else %}
              <i id="like-btn" data-community-id="{{ community.pk }}" class="bi bi-heart text-danger"></i> 
          {% endif %}
        {% endif %}
        <span id="like-count">{{ community.like_users.count }}</span>
      </div>
      <hr class="commu_hr_2">
    </div>
    <!-- 댓글 작성 -->
    <div>
      {% if request.user.is_authenticated %}
      <form id="comment-form" data-community-id="{{ community.pk }}">
        {% csrf_token %}
        {% bootstrap_form community_comment_form layout='inline' %}
        <div class="d-flex justify-content-end mt-3">
          <input class="detail_write my-3" type="submit" value="댓글 작성"></input>
        </div>
      </form>
      <br>
      {% endif %}
      <hr class="commu_hr_2">
      <!-- 댓글 현황 -->
      <div id="comments">
        {% for comment in comments %}
        <div class="d-flex justify-content-between">
          <div class="d-flex">
          {% if comment.user.image %}
          <img src="{{ comment.user.image.url }}" class="commu_pf_img mx-2 my-2" alt="유저 이미지">
          {% else %}
          {% comment %} <img src="{% static 'img/no-avatar.jpg' %}" class="commu_pf_img text" alt="유저 대체이미지"> {% endcomment %}
          {% endif %}
          <p> {{ comment.content }}</p>
        </div>
        <div class="my-2">
          {% if request.user == comment.user %}
            <form action="{% url 'articles:community_comment_delete' comment.pk %}" method="POST" class="my-0">
              {% csrf_token %}
              <input type="submit" class="btn btn-outline-danger mx-2" value="삭제">
            </form>
          {% endif %} 
        </div>
        </div>
        <hr class="commu_hr_2">
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock content %}

{% block script %}
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>
  let slideIndex = 1;
  showSlides(slideIndex);
  
  function plusSlides(n) {
    showSlides(slideIndex += n);
  }
  
  function currentSlide(n) {
    showSlides(slideIndex = n);
  }
  
  function showSlides(n) {
  let i;
  let slides = document.getElementsByClassName("mySlides");
  let dots = document.getElementsByClassName("dot");
  if (n > slides.length) {slideIndex = 1}
  if (n < 1) {slideIndex = slides.length}
  for (i = 0; i < slides.length; i++) {
    slides[i].style.display = "none";
  }
  for (i = 0; i < dots.length; i++) {
    dots[i].className = dots[i].className.replace(" active", "");
  }
  slides[slideIndex-1].style.display = "block";
  dots[slideIndex-1].className += " active";
  }
</script>

<script>
  // 댓글
  const commentForm = document.querySelector('#comment-form')

  const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value
  commentForm.addEventListener('submit', function() {
    event.preventDefault();
    axios({
      method: 'post',
      url: `/${event.target.dataset.communityId}/community_comment_create/`,
      headers: {'X-CSRFToken': csrftoken},
      data: new FormData(commentForm)
    })
    .then(response => {
      console.log(response.data)
      const comments = document.querySelector('#comments')
      comments.insertAdjacentHTML('beforeend', `
      <div class="d-flex">
        <img src="${ response.data.userImg }" class="commu_pf_img mx-2 my-2">
        <p>${ response.data.content }</p>
      </div>
      <hr class="commu_detail_hr">
      `)
      commentForm.reset()
    })
  })
</script>


<script>
  // 좋아요
  const likeBtn = document.querySelector('#like-btn')
  likeBtn.addEventListener('click', function (event) {
      console.log(event.target.dataset)
      axios({
          method: 'get',
          url: `/${event.target.dataset.communityId}/community_like/`
      })
      .then(response => {
          console.log(response)
          console.log(response.data)
          if (response.data.isLiked === true) {
              event.target.classList.add('bi-heart-fill')
              event.target.classList.remove('bi-heart')
          } else {
              event.target.classList.add('bi-heart')
              event.target.classList.remove('bi-heart-fill')
          }
          const likeCount = document.querySelector('#like-count')
          likeCount.innerText = response.data.likeCount
      })
  })
</script>

<!-- MDB -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.0.1/mdb.min.js"></script>
{% endblock script %}

articles/templates/articles/community_form.html
{% extends 'base.html' %}

{% load static %}
{% load widget_tweaks %}
{% load django_bootstrap5 %}
{% load imagekit %}

{% block title %} | 새 글 쓰기{% endblock title %}
{% block style %}
<style>
  .form_container {
    height: auto;
    background-image: url(/static/img/background.jpg);
    background-repeat : no-repeat;
    background-size : cover;
    background-position: center;
  }
</style>
{% endblock style %}

{% block content %}
  <section class="form_container d-flex justify-content-center">
    <div class="commu-form-wrapper">
      <form action="" method="POST" enctype="multipart/form-data">
        <div class="d-flex justify-content-center">
          <h2 class="review_write mb-5">글쓰기</h2>
        </div>
        {% csrf_token %}
        {{ community_form.media }}
        <label for="title" class="form-label">제목</label>
        {% render_field community_form.title class="commu-input form-control" placeholder="글제목을 입력해주세요" %}
        <label for="title" class="form-label mt-3">내용</label>
        {% render_field community_form.content %}
        <label for="images" class="form-label mt-3">사진 첨부</label>
        {% render_field community_images_form.images class="commu-input form-control" %}
        <div class="d-flex justify-content-center mt-5">
          {% if request.resolver_match.url_name == 'community_update' %}
          <input class="commu_btn px-5" type="submit" value="글 수정">
          {% else %}
          <input class="commu_btn px-5" type="submit" value="작성 완료">
          {% endif %}
        </div>
      </form>
    </div><!--commu-form-wrapper-->
  </section>
{% endblock content %}

{% block script %}{% endblock script %}

articles/templates/articles/community_index.html
{% extends 'base.html' %}
{% include 'community_detail' %}

{% load static %}
{% load widget_tweaks %}
{% load django_bootstrap5 %}
{% load imagekit %}

{% block content %}
<section class="containe content-wrapper">
  <div class="write-btn-wrapper">
    <h1>커뮤니티</h1>
    <a class="write-btn" href="{% url 'articles:community_create' %}"><span><i class="fa-solid fa-pen"></i> 글쓰기</span></a>
  </div>
  <hr class="commu_hr">
  <div class="table-wrapper">
    <table class="commu_table w-100">
      <tr class="text-center">
        <td class="commu_num">번호</td>
        <td class="commu_title">제목</td>
        <td class="commu_name">작성자</td>
        <td class="commu_date">작성일</td>
        <td class="commu_view"><i class="bi bi-eye"></i></td>
        <td class="commu_like"><i class="bi bi-star"></i></td>
      </tr>
      {% for community in communities %}
      <tr class="text-center">
        <td>{{ community.id }}</td>
        <td class="text-start text-center">
          <a href="{% url 'articles:community_detail' community.pk %}">{{ community.title }}</a>
        </td>
        <td>{{ community.user.nickname }}</td>
        <td>{{ community.created_at.date }}</td>
        <td>{{ community.hits }}</td>
        <td>{{ community.like_users.count }}</td>
      </tr>
      {% endfor %}
    </table>  
  </div>
  <!-- 페이징처리 시작 -->
  <ul class="pagination justify-content-center py-4">
    <!-- 이전페이지 -->
    {% if communities.has_previous %}
      <li class="page-item d-flex flex-row">
        <a class="page-link" href="?page=1/"><i class="fa-solid fa-backward-step"></i></a>
        <a class="page-link" href="?page={{ communities.previous_page_number }}"><i class="fa-solid fa-chevron-left"></i></a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#"><i class="fa-solid fa-chevron-left"></i></a>
      </li>
    {% endif %}
    <!-- 페이지리스트 -->
    {% for page_number in communities.paginator.page_range %}
      {% if page_number >= communities.number|add:-2 and page_number <= communities.number|add:2 %}
        {% if page_number == communities.number %}  
          <li class="page-item active" aria-current="page">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
          </li>
        {% endif %}
      {% endif %}
    {% endfor %}
    <!-- 다음페이지 -->
    {% if communities.has_next %}
      <li class="page-item d-flex flex-row">
        <a class="page-link" href="?page={{ communities.next_page_number }}"><i class="fa-solid fa-chevron-right"></i></a>
        <a class="page-link" href="?page={{ communities.paginator.num_pages }}"><i class="fa-solid fa-forward-step"></i></a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#"><i class="fa-solid fa-chevron-right"></i></a>
      </li>
    {% endif %}
  </ul>
  <!-- 페이징처리 끝 -->
</section>
{% endblock content %}
{% block script %}{% endblock script %}

articles/templates/articles/product_create.html
{% extends 'base.html' %}

{% load static %}
{% load widget_tweaks %}
{% load django_bootstrap5 %}
{% load imagekit %}

{% block title %} | 상품등록{% endblock title %}
{% block style %}{% endblock style %}

{% block content %}
  <section class="content-wrapper">
    <form action="{% url 'articles:product_create' %}" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form product_form %}
      {% bootstrap_form product_images_form %}
      {% bootstrap_button button_type='submit' content='생성' %}
    </form>
    <a href="{% url 'articles:index' %}">메인화면</a>
  </section>
{% endblock content %}

{% block script %}{% endblock script %}

articles/templates/articles/review_create.html
{% extends 'base.html' %}

{% load static %}
{% load widget_tweaks %}
{% load django_bootstrap5 %}
{% load imagekit %}

{% block title %}{% endblock title %}
{% block style %}
<style>
  .form_container {
    background-image: url(/static/img/background.jpg);
    background-repeat : no-repeat;
    background-size : cover;
    background-position: center;
  }
</style>
{% endblock style %}

{% block content %}
  <section class="form_container">
    <div class="review_c">
      <div class="d-flex justify-content-center">
        <form class="review_form" action="" method="POST" enctype="multipart/form-data">
          <div class="d-flex justify-content-center">
            <h2 class="review_write mb-5">후기 작성</h2>
          </div>
          {% csrf_token %}
          {% bootstrap_form review_form %}
          <div class="text-center mt-5">
            <input class="review_btn px-5" type="submit" value="작성 완료">
          </div>
        </form>
      </div>
    </div>
  </section>
{% endblock content %}
{% block script %}{% endblock script %}

articles/templates/articles/review_update.html
{% extends 'base.html' %}

{% load static %}
{% load widget_tweaks %}
{% load django_bootstrap5 %}
{% load imagekit %}

{% block title %}{% endblock title %}
{% block style %}
<style>
  .content-wrapper {
    background-image: url(/static/img/background.jpg);
    background-repeat : no-repeat;
    background-size : cover;
    background-position: center;
  }
</style>
{% endblock style %}
	
{% block content %}
<section class="content-wrapper">
	<div class="review_c">
		<div class="d-flex justify-content-center">
			<div class="review_form">
				<form action="" method="POST" enctype="multipart/form-data">
					<div class="d-flex justify-content-center">
						<h2 class="review_write mb-5">후기 수정</h2>
					</div>
					{% csrf_token %}
					{% bootstrap_form review_form %}
					<div class="d-flex justify-content-center mt-5">
						<input class="review_btn px-5" type="submit" value="수정">
						<!-- 삭제모달 버튼 -->
						<button type="button" class="review_btn px-5 mx-3" data-bs-toggle="modal" data-bs-target="#exampleModal">
							삭제
						</button>
					</div>
					<!-- 삭제모달 -->
				</form>
				<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
					<div class="modal-dialog">
						<div class="modal-content">
							<div class="modal-body">
								<span class="text-danger">후기를 삭제하면 관련된 모든 댓글이 사라집니다.<br> 그래도 삭제하시겠습니까?</span>
							</div>
							<div class="modal-footer">
								<form action="{% url 'articles:review_delete' review.product.pk review.pk %}" method="POST">
									{% csrf_token %}
									<input class="btn btn-outline-danger btn-sm" type="submit" value="삭제">
								</form>
								<button type="button" class="btn btn-outline-secondary btn-sm" data-bs-dismiss="modal">아니오</button>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock content %}
{% block script %}{% endblock script %}

articles/templates/articles/search.html
{% extends 'base.html' %}

{% load static %}
{% load widget_tweaks %}
{% load django_bootstrap5 %}
{% load imagekit %}
{% load humanize %}

{% block content %}
<section class="container" style="min-height: calc(100% - 180px); margin-top: 300px;">
  <form role="search" class="s_form d-flex" action="{% url 'articles:search' %}" method='GET'>
    <!-- 카테고리 선택 -->
    <select name="field" class="select border rounded-2" aria-label="default select example">
      <option value="all">모두</option>
      {% for i in categories %}
      <option value="{{ i.0 }}">{{ i.1 }}</option>
      {% endfor %}
    </select>
    <!-- 검색어 입력 -->
    <div class="search">
      <input class="s_input w-100 h-100" name="q" type="search" placeholder="검색어를 입력해주세요" aria-label="Search">
      <button class="btnClear" type="reset">
        <img src="https://img.icons8.com/ios/512/cancel.png" alt="">
      </button>
      <button class="btnSearch" type="submit">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </form>
  <div class="container_z">
    <!-- 안내 문구 -->
    <p class="my-5">{{ query }} 검색결과</p>
    <!-- 상품 목록 -->
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 row-cols-lg-3 row-cols-xl-4 my-5" >
      {% for product in products %}
      <a href="{% url 'articles:product_detail' product.pk %}">
        <div class="col d-flex justify-content-center mb-5">
          <div class="card">
            <div class="card-img">
              <img class="w-100 h-100 rounded" src="{{ product.productimages_set.all.0.images }}" alt="product.productimages_set.all.0.images">
            </div>
            <div>
              <div>{{ product.title }}</div>
              <p class='text-secondary fs-6 m-0'>{{ product.brand }}</p>
              <div class="fs-5 mt-2">
                <span class="fw-bold text-dark">{{ product.price|intcomma }}원</span>
              </div>
            </div>
          </div>
        </div>
      </a>
      {% endfor %}
    </div>
  </div>
</section>
{% endblock content %}
{% block script %}{% endblock script %}